#PBS -N EBI-BLAST
#PBS -l nodes=1:ppn=1
#PBS -l mem=1gb
#PBS -l walltime=24:00:00
#PBS -q inferno     
#PBS -A GT-ktk3-CODA20
#PBS -o 00a_log/00a_ebi_blast.out
#PBS -e 00a_log/00a_ebi_blast.err

# This script builds the gene clusters
cd $PBS_O_WORKDIR

# path to ebi blast script
ebi_blast='/storage/home/hcoda1/9/rconrad6/p-ktk3-0/02_ROCker/00c_Scripts//01a_ebi_ncbiblast.py'

# executes the command Run 30 sequences at a time from 1 fasta file.
python ${ebi_blast} --email rotheconrad@gatech.edu --program blastp --stype protein \
--sequence $fasta --database uniprotkb --multifasta --useSeqId --maxJobs 30 --pollFreq 60 \
--outformat ids --exp 10 --alignments 1000

## Run Log:
## qsub -v fasta=00b_curated_seqs/ncbi_refgenes_mcr_renamed_reduced.fasta ../00b_PBS/01a_ebi_blast.pbs
