#PBS -N TrimAl
#PBS -l nodes=1:ppn=1
#PBS -l mem=5gb
#PBS -l walltime=12:00:00
#PBS -q inferno     
#PBS -A GT-ktk3-CODA20
#PBS -o 00a_log/02e_seq_trim_${n}.out
#PBS -e 00a_log/02e_seq_trim_${n}.err

# Change to working directory
cd $PBS_O_WORKDIR

trimal=/storage/coda1/p-ktk3/0/rconrad6/apps/trimal/source/./trimal

${trimal} -in ${input} -out ${output} -resoverlap 0.75 -seqoverlap 80 -automated1

## Run Log ##
## qsub -v input=fasta.aln,output=fasta.aln,n= ../00b_PBS/02e_seq_trim.pbs
## qsub -v input=01_Retrieved_Sequence/LnuF_Concatenated_Deduplicated.fasta.aln,output=01_Retrieved_Sequence/trimal_LnuF_Concatenated_Deduplicated.fasta.aln ../00b_PBS/00c_TrimAl.pbs 
## qsub -v input=02a_tree_prep/02_mmseqs_reps.fasta.aln,output=02a_tree_prep/03_trimmed.fasta.aln,n=mcr ../00b_PBS/02e_seq_trim.pbs

## Param key:
## -resoverlap: Minimum overlap of a positions with other positions in the column to be considered a "good position". Range: [0 - 1]. (see User Guide).
## -seqoverlap: Minimum percentage of "good positions" that a sequence must have in order to be conserved. Range: [0 - 100](see User Guide).
