#PBS -N RAxML-D
#PBS -l nodes=1:ppn=8
#PBS -l mem=10gb
#PBS -l walltime=24:00:00
#PBS -q inferno     
#PBS -A GT-ktk3-CODA20
#PBS -o 00a_log/02f_RAxML-D_${name}.out
#PBS -e 00a_log/02f_RAxML-D_${name}.err

# Load the modules for RAxML
module load raxml/8.2.11-mva2

# Change to working directory
cd $PBS_O_WORKDIR

# set some veriables.
pre=`pwd`/${output}
out=${name}.RAxML

if [ ! -d ${output} ]; then mkdir ${output}; fi

# Run RAxML for amino acid sequence
# Bootstrapped maximum likelihood tree
#raxmlHPC-PTHREADS-AVX -s ${input} -n ${out} -w ${pre} -m PROTGAMMAAUTO -f a -N autoMRE -p 4564821 -T 8 -x 1235

# single ML distance tree
raxmlHPC-PTHREADS-AVX -s ${input} -n ${out} -w ${pre} -m PROTGAMMAAUTO -f x -p 4564821 -T 8

## Run Log ##
## qsub -v input=fasta.aln,output=directory,name=jobname ../00b_PBS/00d_RAxML_AminoAcid.pbs
## qsub -v input=01_Retrieved_Sequence/trimal_LnuF_Blast_Similar_vs_Verified_blast_fltrd.fasta.aln,output=02_RAxML,name=LnuF_filtered_trimmed ../00b_PBS/00d_RAxML_AminoAcid.pbs
## qsub -v input=02a_tree_prep/03_trimmed.fasta.aln,output=04a_RAxML-Distance,name=MCL_distance ../00b_PBS/02f_RAxML_AminoAcid-Distance.pbs 
